drop table if exists bookmarks;

create table bookmarks (
  id integer primary key generated by default as identity,
  title text,
  url text,
  description text,
  rating integer
);

insert into bookmarks (title, url, description, rating)
values
  --('title', 'url', 'description', 'rating');